apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datashare
  namespace: datashare
  labels:
    app.kubernetes.io/name: datashare
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1g"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/limit-rps: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: datashare.example.com
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 7777
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
