apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datashare

resources:
  - namespace.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - backend/configmap.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/pvc.yaml
  - frontend/configmap.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: datashare
  app.kubernetes.io/managed-by: kustomize
